version: '3'
services:
  ubuntu-test:
    container_name: node
    image: ubuntu
    restart: "no"
    command: tail -f /dev/null
    ports:
      - "80:80"
    volumes:
      # nginx服务配置
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "./web:/web"
      # 相关日志
      - "./logs/pm2:/root/.pm2/logs/"
      - "./logs/nginx:/var/log/nginx"